### ISSUE TITLE
Minor typo: reaply -> reapply/ minimise ->minimize / conflics ->conflicts

### ISSUE THREAD

**Issue by birgitpolkner** [citrix/delivery-controller-sdk#12]
https://github.com/citrix/delivery-controller-sdk/blob/master/docs/AppLibrary/Get-AppLibAppDiskAppDNARecommendedOrder.md

Description<br>-----------<br>Finds the disks belonging to the desktop group named "My group" and finds the best order in which to **reaply** these to **minimise** layering **conflics**.

**Comment by ajitchelat** [comment]
Fixed.
